//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("2018.08.11.1718")]
[assembly: AssemblyFileVersion("2018.08.11.1718")]

