//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("2018.06.18.2301")]
[assembly: AssemblyFileVersion("2018.06.18.2301")]

