//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("2018.08.16.1113")]
[assembly: AssemblyFileVersion("2018.08.16.1113")]

