using Innovator.Client.Model;
using M = Innovator.Client.Model;

namespace Innovator.Client
{
  /// <summary>
  /// Creates an instance of a strongly-typed class (which inherits from <see cref="Item"/>) that 
  /// represents a specific item type
  /// </summary>
  /// <seealso cref="Innovator.Client.IItemFactory" />
  /// <remarks>
  /// For any core Aras item type, a model from the <see cref="Innovator.Client.Model"/> namespace
  /// will be returned.  In all other cases, a <c>null</c> will be returned and an 
  /// <see cref="Item"/> will be created
  /// </remarks>
  public class DefaultItemFactory : IItemFactory
  {
    /// <summary>
    /// Creates an instance of a strongly-typed class (which inherits from <see cref="Item" />) that
    /// represents the item type <paramref name="type" />
    /// </summary>
    /// <param name="factory">Factory to be passed to the <see cref="Item" /> constructor</param>
    /// <param name="type">Item type name</param>
    /// <returns>
    /// For any core Aras item type, a model from the <see cref="Innovator.Client.Model"/> namespace
    /// will be returned.  In all other cases, an <see cref="Item"/> will be returned
    /// </returns>
    public Item NewItem(ElementFactory factory, string type)
    {
      switch (type)
      {
        case "Access": return new Access(factory);
        case "Access_ExplicitDefine": return new Access_ExplicitDefine(factory);
        case "Access_ItemClassification": return new Access_ItemClassification(factory);
        case "Access_PropertyValue": return new Access_PropertyValue(factory);
        case "Action": return new M.Action(factory);
        case "Activity": return new Activity(factory);
        case "Activity Assignment": return new ActivityAssignment(factory);
        case "Activity EMail": return new ActivityEMail(factory);
        case "Activity Method": return new ActivityMethod(factory);
        case "Activity Task": return new ActivityTask(factory);
        case "Activity Task Value": return new ActivityTaskValue(factory);
        case "Activity Template": return new ActivityTemplate(factory);
        case "Activity Template Assignment": return new ActivityTemplateAssignment(factory);
        case "Activity Template EMail": return new ActivityTemplateEMail(factory);
        case "Activity Template Method": return new ActivityTemplateMethod(factory);
        case "Activity Template Task": return new ActivityTemplateTask(factory);
        case "Activity Template Transition": return new ActivityTemplateTransition(factory);
        case "Activity Template Variable": return new ActivityTemplateVariable(factory);
        case "Activity Transition": return new ActivityTransition(factory);
        case "Activity Variable": return new ActivityVariable(factory);
        case "Activity Variable Value": return new ActivityVariableValue(factory);
        case "Alias": return new Alias(factory);
        case "Allowed Permission": return new AllowedPermission(factory);
        case "Allowed Workflow": return new AllowedWorkflow(factory);
        case "Applied Updates": return new AppliedUpdates(factory);
        case "Base Notification Message": return new BaseNotificationMessage(factory);
        case "Board": return new Board(factory);
        case "Body": return new Body(factory);
        case "Business Calendar Exception": return new BusinessCalendarException(factory);
        case "Business Calendar Year": return new BusinessCalendarYear(factory);
        case "Can Add": return new CanAdd(factory);
        case "cfg_Enum": return new cfg_Enum(factory);
        case "cfg_NamedConstant": return new cfg_NamedConstant(factory);
        case "cfg_Rule": return new cfg_Rule(factory);
        case "cfg_RuleVariable": return new cfg_RuleVariable(factory);
        case "cfg_Scope": return new cfg_Scope(factory);
        case "cfg_ScopeRule": return new cfg_ScopeRule(factory);
        case "cfg_ScopeVariable": return new cfg_ScopeVariable(factory);
        case "cfg_Variable": return new cfg_Variable(factory);
        case "Chart": return new Chart(factory);
        case "Chart Series": return new ChartSeries(factory);
        case "Client Event": return new ClientEvent(factory);
        case "cmf_AdditionalPropertyType": return new cmf_AdditionalPropertyType(factory);
        case "cmf_BaseView": return new cmf_BaseView(factory);
        case "cmf_ComputedProperty": return new cmf_ComputedProperty(factory);
        case "cmf_ComputedPropertyDependency": return new cmf_ComputedPropertyDependency(factory);
        case "cmf_ContentElementItems": return new cmf_ContentElementItems(factory);
        case "cmf_ContentItems": return new cmf_ContentItems(factory);
        case "cmf_ContentPropertyItems": return new cmf_ContentPropertyItems(factory);
        case "cmf_ContentType": return new cmf_ContentType(factory);
        case "cmf_ContentTypeExportRel": return new cmf_ContentTypeExportRel(factory);
        case "cmf_ContentTypeExportSetting": return new cmf_ContentTypeExportSetting(factory);
        case "cmf_ContentTypeExportToExcel": return new cmf_ContentTypeExportToExcel(factory);
        case "cmf_ContentTypeGridLayout": return new cmf_ContentTypeGridLayout(factory);
        case "cmf_ContentTypeView": return new cmf_ContentTypeView(factory);
        case "cmf_DocumentLifeCycleState": return new cmf_DocumentLifeCycleState(factory);
        case "cmf_ElementAllowedPermission": return new cmf_ElementAllowedPermission(factory);
        case "cmf_ElementBinding": return new cmf_ElementBinding(factory);
        case "cmf_ElementType": return new cmf_ElementType(factory);
        case "cmf_ExportToExcelViewConfig": return new cmf_ExportToExcelViewConfig(factory);
        case "cmf_PropertyAllowedPermission": return new cmf_PropertyAllowedPermission(factory);
        case "cmf_PropertyBinding": return new cmf_PropertyBinding(factory);
        case "cmf_PropertyType": return new cmf_PropertyType(factory);
        case "cmf_Style": return new cmf_Style(factory);
        case "cmf_TabularView": return new cmf_TabularView(factory);
        case "cmf_TabularViewColumn": return new cmf_TabularViewColumn(factory);
        case "cmf_TabularViewColumnGroups": return new cmf_TabularViewColumnGroups(factory);
        case "cmf_TabularViewHeaderRow": return new cmf_TabularViewHeaderRow(factory);
        case "cmf_TabularViewHeaderRows": return new cmf_TabularViewHeaderRows(factory);
        case "cmf_TabularViewTree": return new cmf_TabularViewTree(factory);
        case "Column Event": return new ColumnEvent(factory);
        case "CommandBarButton": return new CommandBarButton(factory);
        case "CommandBarCheckbox": return new CommandBarCheckbox(factory);
        case "CommandBarDropDown": return new CommandBarDropDown(factory);
        case "CommandBarEdit": return new CommandBarEdit(factory);
        case "CommandBarItem": return new CommandBarItem(factory);
        case "CommandBarMenu": return new CommandBarMenu(factory);
        case "CommandBarMenuButton": return new CommandBarMenuButton(factory);
        case "CommandBarMenuCheckbox": return new CommandBarMenuCheckbox(factory);
        case "CommandBarMenuSeparator": return new CommandBarMenuSeparator(factory);
        case "CommandBarSection": return new CommandBarSection(factory);
        case "CommandBarSectionDependency": return new CommandBarSectionDependency(factory);
        case "CommandBarSectionItem": return new CommandBarSectionItem(factory);
        case "CommandBarSeparator": return new CommandBarSeparator(factory);
        case "CommandBarShortcut": return new CommandBarShortcut(factory);
        case "Configurable Grid Event": return new ConfigurableGridEvent(factory);
        case "ConversionRule": return new ConversionRule(factory);
        case "ConversionRuleEventHandler": return new ConversionRuleEventHandler(factory);
        case "ConversionRuleEventTemplate": return new ConversionRuleEventTemplate(factory);
        case "ConversionRuleFileType": return new ConversionRuleFileType(factory);
        case "ConversionServer": return new ConversionServer(factory);
        case "ConversionServerConverterType": return new ConversionServerConverterType(factory);
        case "ConversionServerPriority": return new ConversionServerPriority(factory);
        case "ConversionTask": return new ConversionTask(factory);
        case "ConversionTaskDependency": return new ConversionTaskDependency(factory);
        case "ConversionTaskEventHandler": return new ConversionTaskEventHandler(factory);
        case "ConversionTaskHandlerError": return new ConversionTaskHandlerError(factory);
        case "ConversionTaskResult": return new ConversionTaskResult(factory);
        case "ConverterType": return new ConverterType(factory);
        case "Core_GlobalLayout": return new Core_GlobalLayout(factory);
        case "Core_ItemGridLayout": return new Core_ItemGridLayout(factory);
        case "Core_RelGridLayout": return new Core_RelGridLayout(factory);
        case "Core_SearchCountModeException": return new Core_SearchCountModeException(factory);
        case "CuiDependency": return new CuiDependency(factory);
        case "Dashboard": return new Dashboard(factory);
        case "Dashboard Chart": return new DashboardChart(factory);
        case "DatabaseUpgrade": return new DatabaseUpgrade(factory);
        case "DatabaseUpgradeLogFile": return new DatabaseUpgradeLogFile(factory);
        case "DatabaseUpgradePatch": return new DatabaseUpgradePatch(factory);
        case "Desktop": return new Desktop(factory);
        case "Discussion": return new Discussion(factory);
        case "DiscussionDefinition": return new DiscussionDefinition(factory);
        case "DiscussionDefinitionView": return new DiscussionDefinitionView(factory);
        case "DiscussionTemplate": return new DiscussionTemplate(factory);
        case "DiscussionTemplateView": return new DiscussionTemplateView(factory);
        case "EMail Message": return new EMailMessage(factory);
        case "ES_Admin": return new ES_Admin(factory);
        case "ES_Agent": return new ES_Agent(factory);
        case "ES_AgentState": return new ES_AgentState(factory);
        case "ES_Crawler": return new ES_Crawler(factory);
        case "ES_CrawlerState": return new ES_CrawlerState(factory);
        case "ES_IndexedConfiguration": return new ES_IndexedConfiguration(factory);
        case "ES_IndexedConfigurationType": return new ES_IndexedConfigurationType(factory);
        case "ES_IndexedFile": return new ES_IndexedFile(factory);
        case "ES_IndexedProperty": return new ES_IndexedProperty(factory);
        case "ES_IndexedType": return new ES_IndexedType(factory);
        case "ES_IndexedTypePoly": return new ES_IndexedTypePoly(factory);
        case "ES_IndexQueue": return new ES_IndexQueue(factory);
        case "ES_Search": return new ES_Search(factory);
        case "ES_Settings": return new ES_Settings(factory);
        case "ES_TrackingRelationshipPoly": return new ES_TrackingRelationshipPoly(factory);
        case "ES_UserMapping": return new ES_UserMapping(factory);
        case "ES_VersionedPropertyPoly": return new ES_VersionedPropertyPoly(factory);
        case "Exclusion": return new Exclusion(factory);
        case "Feature License": return new FeatureLicense(factory);
        case "Feed": return new Feed(factory);
        case "FeedTemplate": return new FeedTemplate(factory);
        case "Field": return new Field(factory);
        case "Field Event": return new FieldEvent(factory);
        case "File": return new File(factory);
        case "FileContainerItems": return new FileContainerItems(factory);
        case "FileContainerLocator": return new FileContainerLocator(factory);
        case "FileExchangePackage": return new FileExchangePackage(factory);
        case "FileExchangePackageFile": return new FileExchangePackageFile(factory);
        case "FileExchangeTxn": return new FileExchangeTxn(factory);
        case "FileExchangeTxnState": return new FileExchangeTxnState(factory);
        case "FileGroup": return new FileGroup(factory);
        case "FileGroup File": return new FileGroupFile(factory);
        case "FileSelector": return new FileSelector(factory);
        case "FileSelectorTemplate": return new FileSelectorTemplate(factory);
        case "FileType": return new FileType(factory);
        case "Filter Value": return new FilterValue(factory);
        case "Form": return new Form(factory);
        case "Form Event": return new FormEvent(factory);
        case "Forum": return new Forum(factory);
        case "ForumItem": return new ForumItem(factory);
        case "ForumMessageGroup": return new ForumMessageGroup(factory);
        case "ForumMustViewBy": return new ForumMustViewBy(factory);
        case "ForumSearch": return new ForumSearch(factory);
        case "ForumSharedWith": return new ForumSharedWith(factory);
        case "ForumWantViewBy": return new ForumWantViewBy(factory);
        case "fr_Representation": return new fr_Representation(factory);
        case "fr_RepresentationFile": return new fr_RepresentationFile(factory);
        case "fr_RepresentationType": return new fr_RepresentationType(factory);
        case "fr_RepType_Characteristic": return new fr_RepType_Characteristic(factory);
        case "fr_SupportedFileType": return new fr_SupportedFileType(factory);
        case "Frame": return new Frame(factory);
        case "Frameset": return new Frameset(factory);
        case "GlobalPresentationConfig": return new GlobalPresentationConfig(factory);
        case "Grid": return new Grid(factory);
        case "Grid Column": return new GridColumn(factory);
        case "Grid Event": return new GridEvent(factory);
        case "Help": return new Help(factory);
        case "Help See Also": return new HelpSeeAlso(factory);
        case "Hide In": return new HideIn(factory);
        case "Hide Related In": return new HideRelatedIn(factory);
        case "History": return new History(factory);
        case "History Action": return new HistoryAction(factory);
        case "History Container": return new HistoryContainer(factory);
        case "History Template": return new HistoryTemplate(factory);
        case "History Template Action": return new HistoryTemplateAction(factory);
        case "History Template Where Used": return new HistoryTemplateWhereUsed(factory);
        case "HistorySecureMessage": return new HistorySecureMessage(factory);
        case "Identity": return new Identity(factory);
        case "Implements": return new Implements(factory);
        case "InBasket Task": return new InBasketTask(factory);
        case "Inherited Server Events": return new InheritedServerEvents(factory);
        case "Item Action": return new ItemAction(factory);
        case "Item Report": return new ItemReport(factory);
        case "ItemPresentationConfiguration": return new ItemPresentationConfiguration(factory);
        case "ItemType": return new ItemType(factory);
        case "ItemType Life Cycle": return new ItemTypeLifeCycle(factory);
        case "ItemType_xPropertyDefinition": return new ItemType_xPropertyDefinition(factory);
        case "ITPresentationConfiguration": return new ITPresentationConfiguration(factory);
        case "Language": return new Language(factory);
        case "Life Cycle Map": return new LifeCycleMap(factory);
        case "Life Cycle State": return new LifeCycleState(factory);
        case "Life Cycle Transition": return new LifeCycleTransition(factory);
        case "List": return new List(factory);
        case "Locale": return new Locale(factory);
        case "Located": return new Located(factory);
        case "LockedItems": return new LockedItems(factory);
        case "Member": return new Member(factory);
        case "Message": return new Message(factory);
        case "Message Acknowledgement": return new MessageAcknowledgement(factory);
        case "Method": return new Method(factory);
        case "Metric": return new Metric(factory);
        case "Metric Value": return new MetricValue(factory);
        case "Morphae": return new Morphae(factory);
        case "mp_MacCondition": return new mp_MacCondition(factory);
        case "mp_MacPolicy": return new mp_MacPolicy(factory);
        case "mp_MacPolicyControlledType": return new mp_MacPolicyControlledType(factory);
        case "mp_MacPolicyExemptIdentity": return new mp_MacPolicyExemptIdentity(factory);
        case "mp_PolicyAccessEnvAttribute": return new mp_PolicyAccessEnvAttribute(factory);
        case "mp_PolicyAccessItem": return new mp_PolicyAccessItem(factory);
        case "mpo_MassPromotion": return new mpo_MassPromotion(factory);
        case "mpo_MassPromotionRecord": return new mpo_MassPromotionRecord(factory);
        case "MyReports": return new MyReports(factory);
        case "Old Password": return new OldPassword(factory);
        case "PackageDefinition": return new PackageDefinition(factory);
        case "PackageDependsOn": return new PackageDependsOn(factory);
        case "PackageElement": return new PackageElement(factory);
        case "PackageGroup": return new PackageGroup(factory);
        case "PackageReferencedElement": return new PackageReferencedElement(factory);
        case "PDFWMConfiguration": return new PDFWMConfiguration(factory);
        case "PDFWMTemplates": return new PDFWMTemplates(factory);
        case "Permission": return new Permission(factory);
        case "Permission_ExplicitDefine": return new Permission_ExplicitDefine(factory);
        case "Permission_ItemClassification": return new Permission_ItemClassification(factory);
        case "Permission_PropertyValue": return new Permission_PropertyValue(factory);
        case "Preference": return new Preference(factory);
        case "PreferenceTabTypes": return new PreferenceTabTypes(factory);
        case "PreferenceTypes": return new PreferenceTypes(factory);
        case "PresentableItems": return new PresentableItems(factory);
        case "PresentationCommandBarSection": return new PresentationCommandBarSection(factory);
        case "PresentationConfiguration": return new PresentationConfiguration(factory);
        case "Property": return new M.Property(factory);
        case "qry_QueryDefinition": return new qry_QueryDefinition(factory);
        case "qry_QueryItem": return new qry_QueryItem(factory);
        case "qry_QueryItemSelectProperty": return new qry_QueryItemSelectProperty(factory);
        case "qry_QueryItemSortProperty": return new qry_QueryItemSortProperty(factory);
        case "qry_QueryParameter": return new qry_QueryParameter(factory);
        case "qry_QueryReference": return new qry_QueryReference(factory);
        case "rb_ColumnDefinition": return new rb_ColumnDefinition(factory);
        case "rb_ColumnMapping": return new rb_ColumnMapping(factory);
        case "rb_LocalStyle": return new rb_LocalStyle(factory);
        case "rb_LocalStyleDefinition": return new rb_LocalStyleDefinition(factory);
        case "rb_ParameterViewModel": return new rb_ParameterViewModel(factory);
        case "rb_QueryDefinitionParameterMap": return new rb_QueryDefinitionParameterMap(factory);
        case "rb_TreeGridViewDefinition": return new rb_TreeGridViewDefinition(factory);
        case "rb_TreeRowDefinition": return new rb_TreeRowDefinition(factory);
        case "rb_TreeRowReference": return new rb_TreeRowReference(factory);
        case "rb_UI_ActivateTgvdWizard": return new rb_UI_ActivateTgvdWizard(factory);
        case "rb_UI_CellEditor": return new rb_UI_CellEditor(factory);
        case "rb_UserInputDataSource": return new rb_UserInputDataSource(factory);
        case "ReadPriority": return new ReadPriority(factory);
        case "Relationship Grid Event": return new RelationshipGridEvent(factory);
        case "Relationship View": return new RelationshipView(factory);
        case "RelationshipType": return new RelationshipType(factory);
        case "ReplicationRule": return new ReplicationRule(factory);
        case "ReplicationRuleFileType": return new ReplicationRuleFileType(factory);
        case "ReplicationRuleTargetVault": return new ReplicationRuleTargetVault(factory);
        case "ReplicationTxn": return new ReplicationTxn(factory);
        case "ReplicationTxnLog": return new ReplicationTxnLog(factory);
        case "Report": return new Report(factory);
        case "Revision": return new Revision(factory);
        case "RunReportByUser": return new RunReportByUser(factory);
        case "SavedSearch": return new SavedSearch(factory);
        case "Scheduled Task": return new ScheduledTask(factory);
        case "ScopeCacheDependency": return new ScopeCacheDependency(factory);
        case "Search": return new Search(factory);
        case "Search Center": return new SearchCenter(factory);
        case "Search Criteria": return new SearchCriteria(factory);
        case "SearchMode": return new SearchMode(factory);
        case "SecureMessage": return new SecureMessage(factory);
        case "SecureMessageAudio": return new SecureMessageAudio(factory);
        case "SecureMessageFlaggedBy": return new SecureMessageFlaggedBy(factory);
        case "SecureMessageMarkup": return new SecureMessageMarkup(factory);
        case "SecureMessageVideo": return new SecureMessageVideo(factory);
        case "SecureMessageViewTemplate": return new SecureMessageViewTemplate(factory);
        case "SecureMessageVisibilityFilter": return new SecureMessageVisibilityFilter(factory);
        case "SelfServiceReport": return new SelfServiceReport(factory);
        case "SelfServiceReportFeatured": return new SelfServiceReportFeatured(factory);
        case "SelfServiceReportHelp": return new SelfServiceReportHelp(factory);
        case "SelfServiceReportSettings": return new SelfServiceReportSettings(factory);
        case "SelfServiceReportSharedWith": return new SelfServiceReportSharedWith(factory);
        case "Sequence": return new Sequence(factory);
        case "Server Event": return new ServerEvent(factory);
        case "ServiceProvider": return new ServiceProvider(factory);
        case "SPDocumentLibraryDefinition": return new SPDocumentLibraryDefinition(factory);
        case "SPField": return new SPField(factory);
        case "SQL": return new SQL(factory);
        case "SQL Dependencies": return new SQLDependencies(factory);
        case "SSVC Notification Message": return new SSVCNotificationMessage(factory);
        case "SSVC_Preferences": return new SSVC_Preferences(factory);
        case "SSVCEmailDigestEntry": return new SSVCEmailDigestEntry(factory);
        case "SSVCItems": return new SSVCItems(factory);
        case "SSVCPresentationConfiguration": return new SSVCPresentationConfiguration(factory);
        case "State Distribution": return new StateDistribution(factory);
        case "State EMail": return new StateEMail(factory);
        case "State Notification": return new StateNotification(factory);
        case "StoredSecureMessage": return new StoredSecureMessage(factory);
        case "SystemEvent": return new SystemEvent(factory);
        case "SystemEventHandler": return new SystemEventHandler(factory);
        case "SystemEventLog": return new SystemEventLog(factory);
        case "SystemEventLogDescriptor": return new SystemEventLogDescriptor(factory);
        case "SystemFileContainer": return new SystemFileContainer(factory);
        case "Team": return new Team(factory);
        case "Team Identity": return new TeamIdentity(factory);
        case "TOC Access": return new TOCAccess(factory);
        case "TOC View": return new TOCView(factory);
        case "tp_Image": return new tp_Image(factory);
        case "tp_Item": return new tp_Item(factory);
        case "tp_Stylesheet": return new tp_Stylesheet(factory);
        case "tp_XmlSchema": return new tp_XmlSchema(factory);
        case "tp_XmlSchemaElement": return new tp_XmlSchemaElement(factory);
        case "tp_XmlSchemaOutputSetting": return new tp_XmlSchemaOutputSetting(factory);
        case "Transition Distribution": return new TransitionDistribution(factory);
        case "Transition EMail": return new TransitionEMail(factory);
        case "User": return new User(factory);
        case "UserMessage": return new UserMessage(factory);
        case "Value": return new Value(factory);
        case "Variable": return new Variable(factory);
        case "Vault": return new M.Vault(factory);
        case "View": return new View(factory);
        case "View With": return new ViewWith(factory);
        case "Viewer": return new Viewer(factory);
        case "WMConfiguration": return new WMConfiguration(factory);
        case "WMItemType": return new WMItemType(factory);
        case "WMSet": return new WMSet(factory);
        case "WMSetConfigurations": return new WMSetConfigurations(factory);
        case "WMSettingContent": return new WMSettingContent(factory);
        case "WMSettingLCStates": return new WMSettingLCStates(factory);
        case "WMSettings": return new WMSettings(factory);
        case "WMType": return new WMType(factory);
        case "Workflow": return new Workflow(factory);
        case "Workflow Map": return new WorkflowMap(factory);
        case "Workflow Map Activity": return new WorkflowMapActivity(factory);
        case "Workflow Map Path": return new WorkflowMapPath(factory);
        case "Workflow Map Path Post": return new WorkflowMapPathPost(factory);
        case "Workflow Map Path Pre": return new WorkflowMapPathPre(factory);
        case "Workflow Map Variable": return new WorkflowMapVariable(factory);
        case "Workflow Process": return new WorkflowProcess(factory);
        case "Workflow Process Activity": return new WorkflowProcessActivity(factory);
        case "Workflow Process Path": return new WorkflowProcessPath(factory);
        case "Workflow Process Path Post": return new WorkflowProcessPathPost(factory);
        case "Workflow Process Path Pre": return new WorkflowProcessPathPre(factory);
        case "Workflow Process Variable": return new WorkflowProcessVariable(factory);
        case "Workflow Task": return new WorkflowTask(factory);
        case "WSConfiguration": return new WSConfiguration(factory);
        case "WSType": return new WSType(factory);
        case "WSTypeAction": return new WSTypeAction(factory);
        case "WSTypeAssociate": return new WSTypeAssociate(factory);
        case "WSTypeProperty": return new WSTypeProperty(factory);
        case "xClass": return new xClass(factory);
        case "xClass_Classification_Perm": return new xClass_Classification_Perm(factory);
        case "xClass_xProperty_Flatten": return new xClass_xProperty_Flatten(factory);
        case "xClass_xPropertyDefinition": return new xClass_xPropertyDefinition(factory);
        case "xClass_xPropValue_Perm": return new xClass_xPropValue_Perm(factory);
        case "xClassifiableItem_xClass": return new xClassifiableItem_xClass(factory);
        case "xClassificationTree": return new xClassificationTree(factory);
        case "xClassificationTree_ItemType": return new xClassificationTree_ItemType(factory);
        case "xItemTypeAllowedProperty": return new xItemTypeAllowedProperty(factory);
        case "xPropertyContainerItem": return new xPropertyContainerItem(factory);
        case "xPropertyDefinition": return new xPropertyDefinition(factory);
      }
      return null;
    }
  }
}
